grokonez:
    app:
        jwtExpiration: 86400
        jwtSecret: jwtErotemeSecretKey
server:
    port: 8084
spring:
    datasource:
        password: root123
        url: jdbc:mysql://localhost:3306/userlogin
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            show-sql:true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    rabbitmq:
        host: localhost
        port: 5672
